# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- dev

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: Default
      demands: Agent.Name -equals planimation
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          cd /home/ubuntu/myagent/_work/1/s/server
          docker rm planimation-backend
          docker rmi planimation-backend:latest
          docker build -t planimation-backend:latest -f ./docker/release/Dockerfile ./
          docker run --name planimation-backend -d -p 8080:8080 planimation-backend:latest
          


    